# This is a config for E2B sandbox template.
# You can use template ID (wvf9dzjuoxkgqv2kl5be) or template name (vibe-nextjs-test-10) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-10") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-10") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-10')

team_id = "276585d9-dd32-4708-b9cc-d109eadb7dcb"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-10"
template_id = "wvf9dzjuoxkgqv2kl5be"
